import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import { Montserrat } from "next/font/google";
import { ThemeProvider } from "@/providers/theme-provider";
import Footer from "@/components/Footer/Footer";

// If loading a variable font, you don't need to specify the font weight
const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "FrontSheet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${montserrat.className} antialiased bg-muted`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex flex-col justify-between w-full min-h-dvh">
            <Header />

            {children}

            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
